### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by iherman** [rpserjo/sortable#1]
I would like to use your software in a public document, and was looking for some licensing information. Is there any string attached in using it?

Per information, the goal is to use (if it works, well, still testing) to make the tables in this document sortable: 

https://w3c.github.io/epub-tests/

Thanks.

**Comment by rpserjo** [comment]
There is no license information. It's my test project and I had no intents to license it. But you are free to use it in any ways and cases you want.

**Comment by iherman** [comment]
Thank you, @rpserjo. The function is simple and does what I need, so I will use it; I will put a reference to your repo into the comment.
